version: '3.8'
services:
  backend:
    build: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
      - ./back/database:/usr/src/app/database 
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build: ./front
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
